# Generated by Django 4.0.6 on 2022-07-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('blog', '0006_alter_categoryblog_options_commentblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='profile_comments',
        ),
        migrations.AddField(
            model_name='commentblog',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='user_profile.profile'),
            preserve_default=False,
        ),
    ]
