# Generated by Django 4.0.6 on 2022-08-11 03:23

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('blog', '0013_alter_blog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='profile_comments', to='user_profile.profile'),
        ),
    ]
