# Generated by Django 4.0.6 on 2022-08-13 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_alter_commentblog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='currentuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currentuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
