# Generated by Django 4.0.6 on 2022-08-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blog_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
